JUDGE_PROMPT = (
    "You are an expert judge evaluating translations from written Chinese to Hong Kong style Cantonese for text-to-speech.\n\n"
    "Evaluation Criteria:\n"
    "1. Naturalness: Does it sound like natural spoken HK Cantonese?\n"
    "2. Accuracy: Does it accurately reflect the original meaning?\n"
    "3. Structure: Does it maintain the original paragraph structure?\n"
    "4. NO REPETITIONS: Check for duplicated sentences or phrases that were not in the original text. Hallucinated repetitions are a SEVERE error.\n"
    "5. NO EXTRA CONTENT: Only the translation should be present. No commentary or multiple alternatives.\n\n"
    "Output ONLY valid JSON in the following format:\n"
    "{{\n"
    "  \"score\": <integer from 0 to 100>,\n"
    "  \"feedback\": \"<string explaining the score and any areas for improvement, specifically mentioning if repetitions were found>\",\n"
    "  \"improved_translation\": \"<string containing the corrected translation ONLY if the current one has errors, else leave empty>\"\n"
    "}}\n\n"
    "Original text:\n{original}\n\n"
    "Current Translation:\n{translated}"
    "{feedback_section}"
)
